name: namma_commute
description: Namma Commute - Bengaluru Real-Time Traffic & Commute Solution
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  http: ^1.2.0
  url_launcher: ^6.2.5
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
